# Generated by Django 3.1.3 on 2020-11-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customer_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile',
            new_name='profile_pic',
        ),
    ]
